---
title: "Codebook"
author: "thebloodymummer"
date: "10 March 2018"
output: html_document
---


This codebook provides a description of the Experiment, variables, data and subsequent processing of the raw data into a tidy data set.

## Summary

* This work focuses on colelcted data from accelerometers from the Samsung Galaxy S smartphone. The study was carried out with 30 volunteers between the ages of 19 and 48 while perfoming basic exercises (Walking, Walking upstairs, Walking downstairs, Sitting, Standing, Laying.)

* Further information can be found at
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones.

* Data was extracted from the following zip file, https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip, and subsequently read and processed in Rstudio Version 1.1.419 from the working directory (UCI HAR Dataset). 

* The raw data is initially seperated into training and test sets which are initially merged and any measurements related to the mean or standard deviation are extracted. Each extracted variable is labeled with a descriptive variable name. Subsequently a data set is generated in which the average of each variable for each activity and each subject is presented.

## Files 

The data was presented in the following list of files.

-activity_labels.txt

-features.txt

-features_info.txt
-README.txt

-test/subject_test.txt

-test/X_test.txt

-test/t_test.txt

-test/Iniertial Signals/body_acc_x_test.txt

-test/Iniertial Signals/body_acc_y_test.txt

-test/Iniertial Signals/body_acc_z_test.txt

-test/Iniertial Signals/body_gryo_x_test.txt

-test/Iniertial Signals/body_gryo_y_test.txt

-test/Iniertial Signals/body_gryo_z_test.txt

-test/Iniertial Signals/total_acc_x_test.txt

-test/Iniertial Signals/total_acc_y_test.txt

-test/Iniertial Signals/total_acc_z_test.txt

-train/subject_train.txt

-train/X_train.txt

-train/t_train.txt

-train/Iniertial Signals/body_acc_x_train.txt

-train/Iniertial Signals/body_acc_y_train.txt

-train/Iniertial Signals/body_acc_z_train.txt

-train/Iniertial Signals/body_gryo_x_train.txt

-train/Iniertial Signals/body_gryo_y_train.txt

-train/Iniertial Signals/body_gryo_z_train.txt

-train/Iniertial Signals/total_acc_x_train.txt

-train/Iniertial Signals/total_acc_y_train.txt

-train/Iniertial Signals/total_acc_z_train.txt

##Variables

-tBodyAcc-XYZ

-tGravityAcc-XYZ

-tBodyAccJerk-XYZ

-tBodyGyro-XYZ

-tBodyGyroJerk-XYZ

-tBodyAccMag

-tGravityAccMag

-tBodyAccJerkMag

-tBodyGyroMag

-tBodyGyroJerkMag

-fBodyAcc-XYZ

-fBodyAccJerk-XYZ

-fBodyGyro-XYZ

-fBodyAccMag

-fBodyAccJerkMag

-fBodyGyroMag

-fBodyGyroJerkMag

###The set of variables that were estimated from these signals are: 

-mean(): Mean value

-std(): Standard deviation

-mad(): Median absolute deviation 

-max(): Largest value in array

-min(): Smallest value in array

-sma(): Signal magnitude area

-energy(): Energy measure. Sum of the squares divided by the number of values. 

-iqr(): Interquartile range 

-entropy(): Signal entropy

-arCoeff(): Autorregresion coefficients with Burg order equal to 4

-correlation(): correlation coefficient between two signals

-maxInds(): index of the frequency component with largest magnitude

-meanFreq(): Weighted average of the frequency components to obtain a mean frequency

-skewness(): skewness of the frequency domain signal 

-kurtosis(): kurtosis of the frequency domain signal 

-bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.

-angle(): Angle between to vectors.

## Processing

The file run_analysis.R was written the the following way.

* The reshape and data.table packages were loaded.

* The following data files were imported giving intothe following data frames.

-activity      -     activity_labels.txt

-features      -     features.txt

-subject_train -     train/subject_train.txt

-X_train       -     train/X_train.txt

-y_train       -     train/y_train.txt

-subject_test  -     test/subject_test.txt

-X_test        -     test/X_test.txt

-y_test        -     test/y_test.txt

* The factor names of y_train and y_test were changed according to the factor names given in activity.

-1  -WALKING

-2 - WALKING_UPSTAIRS

-3 - WALKING_DOWNSTAIRS

-4 - SITTING

-5 - STANDING

-6 - LAYING

* Descriptive column headings were provided for the follwing data frames:

-subject_train   -   "Subject"

-subject_test    -   "Subject"

-y_train         -   "Activity"

-y_test          -   "Activity"

-X_train         -   features (2nd column)

-X_test          -   features (2nd column)

* Data frame "Merged" - > New data frame binding the follwing data frames: subject_train, y_train, X_train, subject_test, y_test and X_test.

* Data frames "Merged2" and "Meanstd" - > New data frame isolating features containing "mean" or "std" 

* Vectors "labels" and "labels2" - > Subsequent column labels for tidy data.

* Data Frames "Meanstd2" and "tidy" - > Subsequent tidy data.

* Data file written as "tidy_data.txt"